/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Admin.AdminJFrame;
import Model.Booking;
import Model.Car;
import Model.Carlist;
import User.UserJFrame;

/**
 *
 * @author yashjain
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Carlist history;
    Car car;
    Booking bookHistory;
    AdminJFrame adminJFrame;
    UserJFrame userJFrame;
    public MainJFrame() {
        initComponents();
        history = new Carlist();
        bookHistory = new Booking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        Action = new javax.swing.JPanel();
        User = new javax.swing.JButton();
        Admin = new javax.swing.JButton();
        Workstation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPanel.setBackground(new java.awt.Color(240, 248, 255));
        SplitPanel.setDividerSize(15);

        Action.setBackground(new java.awt.Color(240, 248, 255));
        Action.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 217, 220), 1, true));
        Action.setPreferredSize(new java.awt.Dimension(200, 468));

        User.setBackground(new java.awt.Color(0, 83, 170));
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setText("USER");
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        User.setDoubleBuffered(true);
        User.setFocusCycleRoot(true);
        User.setFocusTraversalPolicyProvider(true);
        User.setPreferredSize(new java.awt.Dimension(129, 37));
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });

        Admin.setBackground(new java.awt.Color(0, 83, 170));
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("ADMIN");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionLayout = new javax.swing.GroupLayout(Action);
        Action.setLayout(ActionLayout);
        ActionLayout.setHorizontalGroup(
            ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ActionLayout.setVerticalGroup(
            ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(Admin)
                .addGap(54, 54, 54)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        ActionLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Admin, User});

        SplitPanel.setLeftComponent(Action);

        Workstation.setBackground(new java.awt.Color(240, 248, 255));
        Workstation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 217, 220), 1, true));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 83, 170));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to TopDrive");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout WorkstationLayout = new javax.swing.GroupLayout(Workstation);
        Workstation.setLayout(WorkstationLayout);
        WorkstationLayout.setHorizontalGroup(
            WorkstationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        WorkstationLayout.setVerticalGroup(
            WorkstationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        SplitPanel.setRightComponent(Workstation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
        userJFrame = new UserJFrame(history, bookHistory);
        userJFrame.setVisible(true);
    }//GEN-LAST:event_UserActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
         adminJFrame = new AdminJFrame(history);
         adminJFrame.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Action;
    private javax.swing.JButton Admin;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JButton User;
    private javax.swing.JPanel Workstation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
