/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Model.Car;
import Model.Carlist;
import UI.MainJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author yashjain
 */
public class AdminJFrames extends javax.swing.JFrame {

    /**
     * Creates new form AdminJFrames
     */
    MainJFrame mainJFrame;
    static Carlist history;
    public AdminJFrames(Carlist history) {
        initComponents();
        this.history = history;
        history.setSelectedView(null);
        history.setSelectedView(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        Action = new javax.swing.JPanel();
        Create = new javax.swing.JButton();
        View = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Details = new javax.swing.JButton();
        Workstation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 248, 255));

        SplitPanel.setBackground(new java.awt.Color(240, 248, 255));
        SplitPanel.setDividerSize(15);

        Action.setBackground(new java.awt.Color(240, 248, 255));
        Action.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 217, 220), 1, true));
        Action.setPreferredSize(new java.awt.Dimension(200, 468));

        Create.setBackground(new java.awt.Color(0, 83, 170));
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("CREATE");
        Create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Create.setDoubleBuffered(true);
        Create.setFocusCycleRoot(true);
        Create.setFocusTraversalPolicyProvider(true);
        Create.setPreferredSize(new java.awt.Dimension(129, 37));
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        View.setBackground(new java.awt.Color(0, 83, 170));
        View.setForeground(new java.awt.Color(255, 255, 255));
        View.setText("VIEW");
        View.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        View.setDoubleBuffered(true);
        View.setFocusCycleRoot(true);
        View.setFocusTraversalPolicyProvider(true);
        View.setPreferredSize(new java.awt.Dimension(129, 37));
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 83, 170));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("LOGOUT");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back.setDoubleBuffered(true);
        Back.setFocusCycleRoot(true);
        Back.setFocusTraversalPolicyProvider(true);
        Back.setPreferredSize(new java.awt.Dimension(129, 37));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Details.setBackground(new java.awt.Color(0, 83, 170));
        Details.setForeground(new java.awt.Color(255, 255, 255));
        Details.setText("DETAILS");
        Details.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Details.setDoubleBuffered(true);
        Details.setFocusCycleRoot(true);
        Details.setFocusTraversalPolicyProvider(true);
        Details.setPreferredSize(new java.awt.Dimension(129, 37));
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionLayout = new javax.swing.GroupLayout(Action);
        Action.setLayout(ActionLayout);
        ActionLayout.setHorizontalGroup(
            ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ActionLayout.setVerticalGroup(
            ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(Action);

        Workstation.setBackground(new java.awt.Color(240, 248, 255));
        Workstation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 217, 220), 1, true));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 83, 170));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to TopDrive");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout WorkstationLayout = new javax.swing.GroupLayout(Workstation);
        Workstation.setLayout(WorkstationLayout);
        WorkstationLayout.setHorizontalGroup(
            WorkstationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkstationLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        WorkstationLayout.setVerticalGroup(
            WorkstationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkstationLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        SplitPanel.setRightComponent(Workstation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        CreateJPanel createJPanel = new CreateJPanel(history);
        SplitPanel.setRightComponent(createJPanel);
    }//GEN-LAST:event_CreateActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        AdminJPanels adminJFrame = new AdminJPanels(history);
        SplitPanel.setRightComponent(adminJFrame);
    }//GEN-LAST:event_ViewActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
//        mainJFrame = new MainJFrame();
        this.dispose();
//        mainJFrame.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        // TODO add your handling code here:
        Car SelectedRow = history.getSelectedView();
       if(SelectedRow != null){
          DetailsJPanel detailsJPanel = new DetailsJPanel(history);
          SplitPanel.setRightComponent(detailsJPanel); 
       }else{
           JOptionPane.showMessageDialog(this, "Please Selected Item From the Table", "Error message", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_DetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrames(history).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Action;
    private javax.swing.JButton Back;
    private javax.swing.JButton Create;
    private javax.swing.JButton Details;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JButton View;
    private javax.swing.JPanel Workstation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
