/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

import UI.*;
import Model.Car;
import Model.Carlist;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author yashjain
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Carlist history;
    String availables = "Yes";
    String mcs = "Yes";
    public CreateJPanel(Carlist history) {
        initComponents();
        this.history = history;     
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        Brand = new javax.swing.JLabel();
        BrandTxt = new javax.swing.JTextField();
        Model = new javax.swing.JLabel();
        ModelTxt = new javax.swing.JTextField();
        ModelNo = new javax.swing.JLabel();
        ModelNoTxt = new javax.swing.JTextField();
        Year = new javax.swing.JLabel();
        YearTxt = new javax.swing.JTextField();
        location = new javax.swing.JLabel();
        LocationTxt = new javax.swing.JTextField();
        Serial = new javax.swing.JLabel();
        SerialTxt = new javax.swing.JTextField();
        Operator = new javax.swing.JLabel();
        OperatorTxt = new javax.swing.JTextField();
        Available = new javax.swing.JLabel();
        AvailableY = new javax.swing.JRadioButton();
        AvailableN = new javax.swing.JRadioButton();
        MC = new javax.swing.JLabel();
        MCY = new javax.swing.JRadioButton();
        MCN = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();
        NameErr = new javax.swing.JLabel();
        BrandErr = new javax.swing.JLabel();
        ModelErr = new javax.swing.JLabel();
        ModelNoErr = new javax.swing.JLabel();
        YearErr = new javax.swing.JLabel();
        LocationErr = new javax.swing.JLabel();
        SerialErr = new javax.swing.JLabel();
        OperatorErr = new javax.swing.JLabel();
        Seat = new javax.swing.JLabel();
        SeatTxt = new javax.swing.JTextField();
        SeatErr = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 248, 255));

        Title.setBackground(java.awt.Color.white);
        Title.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 83, 170));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Create Profile");

        Name.setForeground(new java.awt.Color(72, 72, 72));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Name.setText("Name");

        Brand.setForeground(new java.awt.Color(72, 72, 72));
        Brand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Brand.setText("Car Brand");

        Model.setForeground(new java.awt.Color(72, 72, 72));
        Model.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Model.setText("Car Model");

        ModelNo.setForeground(new java.awt.Color(72, 72, 72));
        ModelNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ModelNo.setText("Car Model No");

        Year.setForeground(new java.awt.Color(72, 72, 72));
        Year.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Year.setText("Manufacture Year");

        location.setForeground(new java.awt.Color(72, 72, 72));
        location.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        location.setText("Location");

        Serial.setForeground(new java.awt.Color(72, 72, 72));
        Serial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Serial.setText("Serial No");

        Operator.setForeground(new java.awt.Color(72, 72, 72));
        Operator.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator.setText("Operator");

        Available.setForeground(new java.awt.Color(72, 72, 72));
        Available.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Available.setText("Available");

        AvailableY.setForeground(new java.awt.Color(72, 72, 72));
        AvailableY.setSelected(true);
        AvailableY.setText("Yes");
        AvailableY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailableYActionPerformed(evt);
            }
        });

        AvailableN.setForeground(new java.awt.Color(72, 72, 72));
        AvailableN.setText("No");
        AvailableN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailableNActionPerformed(evt);
            }
        });

        MC.setForeground(new java.awt.Color(72, 72, 72));
        MC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MC.setText("Maintenance Certificate");

        MCY.setForeground(new java.awt.Color(72, 72, 72));
        MCY.setSelected(true);
        MCY.setText("Yes");
        MCY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCYActionPerformed(evt);
            }
        });

        MCN.setForeground(new java.awt.Color(72, 72, 72));
        MCN.setText("No");
        MCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCNActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(0, 83, 170));
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        NameErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        NameErr.setForeground(java.awt.Color.red);

        BrandErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        BrandErr.setForeground(java.awt.Color.red);

        ModelErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        ModelErr.setForeground(java.awt.Color.red);

        ModelNoErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        ModelNoErr.setForeground(java.awt.Color.red);

        YearErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        YearErr.setForeground(java.awt.Color.red);

        LocationErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        LocationErr.setForeground(java.awt.Color.red);

        SerialErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        SerialErr.setForeground(java.awt.Color.red);

        OperatorErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        OperatorErr.setForeground(java.awt.Color.red);

        Seat.setForeground(new java.awt.Color(72, 72, 72));
        Seat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Seat.setText("Seat");

        SeatErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        SeatErr.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MC, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Brand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Model, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModelNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Year, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Serial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Operator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Available, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Seat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModelNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OperatorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MCY)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MCN)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BrandErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModelErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModelNoErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(YearErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LocationErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SerialErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OperatorErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SeatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeatErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AvailableY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AvailableN)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Brand)
                            .addComponent(BrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrandErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Model)
                            .addComponent(ModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModelErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModelNo)
                            .addComponent(ModelNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModelNoErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Year)
                            .addComponent(YearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YearErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(location)
                            .addComponent(LocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocationErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Serial)
                            .addComponent(SerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SerialErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Operator)
                            .addComponent(OperatorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OperatorErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Seat, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Available)
                            .addComponent(AvailableY)
                            .addComponent(AvailableN))
                        .addGap(18, 18, 18)
                        .addComponent(MC))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MCY)
                        .addComponent(MCN)))
                .addGap(18, 18, 18)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AvailableYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailableYActionPerformed
        // TODO add your handling code here:
        AvailableN.setSelected(false);
        AvailableY.setSelected(true);
        availables = "Yes";
    }//GEN-LAST:event_AvailableYActionPerformed

    private void AvailableNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailableNActionPerformed
        // TODO add your handling code here:
        AvailableN.setSelected(true);
        AvailableY.setSelected(false);
        availables = "No";
    }//GEN-LAST:event_AvailableNActionPerformed

    private void MCYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCYActionPerformed
        // TODO add your handling code here:
        MCY.setSelected(true);
        MCN.setSelected(false);
        mcs = "Yes";
    }//GEN-LAST:event_MCYActionPerformed

    private void MCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCNActionPerformed
        // TODO add your handling code here:
         MCY.setSelected(false);
         MCN.setSelected(true);
         mcs = "No";
    }//GEN-LAST:event_MCNActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String name = NameTxt.getText();
        String brand = BrandTxt.getText();
        String model = ModelTxt.getText();
        String modelNo = ModelNoTxt.getText();
        int year = 0;
        Pattern ptr = Pattern.compile("(19|20|21)[0-9][0-9]", Pattern.CASE_INSENSITIVE);
        String location = LocationTxt.getText();
        String serialNo = SerialTxt.getText();
        String operator = OperatorTxt.getText();
        String avaliable = availables;
        String mc = mcs;
        int seat = 2;
        Boolean isVaild = true;
        
        for(Car i : history.getHistory()){
            if(i.getSerialNo().equals(serialNo)){
                JOptionPane.showMessageDialog(this, "Serial No already present it should be unique", "Error message", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if(name.trim().isEmpty()) {
            NameErr.setText("Name is required");
            isVaild = false;
        }
        else NameErr.setText("");
        
        if(brand.trim().isEmpty()) {
            BrandErr.setText("Brand Name is required");
            isVaild = false;
        }
        else BrandErr.setText("");
        
        if(model.trim().isEmpty()) {
            ModelErr.setText("Model Name is required");
            isVaild = false;
        }
        else ModelErr.setText("");
        
        if(modelNo.trim().isEmpty()){
            ModelNoErr.setText("Model Number is required");
            isVaild = false;
        }
        else ModelNoErr.setText("");
        
        if(serialNo.trim().isEmpty()) {
            SerialErr.setText("Model Number is required");
            isVaild = false;
        }
        else SerialErr.setText("");
        
        if(operator.trim().isEmpty()) {
            OperatorErr.setText("Model Number is required");
            isVaild = false;
        }
        else OperatorErr.setText("");
        
        if(location.trim().isEmpty()) {
            LocationErr.setText("Model Number is required");
            isVaild = false;
        }
        else LocationErr.setText("");
        
        if(!YearTxt.getText().trim().isEmpty()){
        try {
            year = Integer.parseInt(YearTxt.getText());
            if(!ptr.matcher(YearTxt.getText()).matches()){
                YearErr.setText("Year is not proper"); 
                isVaild = false;
            }else{
                YearErr.setText(""); 
            }
            } catch (NumberFormatException nfe) {
                YearErr.setText("Year must be number");
                isVaild = false;
            }
         }else{
            YearErr.setText("Year is required");
        }
        
        if(!SeatTxt.getText().trim().isEmpty()){
        try {
            seat = Integer.parseInt(SeatTxt.getText());
            if(seat < 2 || seat > 60){
             SeatErr.setText("Seat must be min 2 and max 60");
              isVaild = false;
            } else {
                SeatErr.setText("");
            }
            } catch (NumberFormatException nfe) {
                SeatErr.setText("Seat must be number");
                isVaild = false;
            }
         }else{
            SeatErr.setText("Seat is required");
        }
        
        if(isVaild){
            Car car = history.addCarData();
            car.setName(name);
            car.setBrand(brand);
            car.setModel(model);
            car.setModelNo(modelNo);
            car.setYear(year);
            car.setLocation(location);
            car.setSerialNo(serialNo);
            car.setOperator(operator);
            car.setAvaliable(avaliable);
            car.setMc(mc);
            car.setSeat(seat);

            JOptionPane.showMessageDialog(this, "Data Added Successfully");  
            DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");  
            Date today = Calendar.getInstance().getTime();  
            history.setUpdateDate(dateFormat.format(today));

            NameTxt.setText("");
            BrandTxt.setText("");
            ModelTxt.setText("");
            ModelNoTxt.setText("");
            YearTxt.setText("");
            LocationTxt.setText("");
            SerialTxt.setText("");
            OperatorTxt.setText("");
            SeatTxt.setText("");
        }
    }//GEN-LAST:event_SubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Available;
    private javax.swing.JRadioButton AvailableN;
    private javax.swing.JRadioButton AvailableY;
    private javax.swing.JLabel Brand;
    private javax.swing.JLabel BrandErr;
    private javax.swing.JTextField BrandTxt;
    private javax.swing.JLabel LocationErr;
    private javax.swing.JTextField LocationTxt;
    private javax.swing.JLabel MC;
    private javax.swing.JRadioButton MCN;
    private javax.swing.JRadioButton MCY;
    private javax.swing.JLabel Model;
    private javax.swing.JLabel ModelErr;
    private javax.swing.JLabel ModelNo;
    private javax.swing.JLabel ModelNoErr;
    private javax.swing.JTextField ModelNoTxt;
    private javax.swing.JTextField ModelTxt;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameErr;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel Operator;
    private javax.swing.JLabel OperatorErr;
    private javax.swing.JTextField OperatorTxt;
    private javax.swing.JLabel Seat;
    private javax.swing.JLabel SeatErr;
    private javax.swing.JTextField SeatTxt;
    private javax.swing.JLabel Serial;
    private javax.swing.JLabel SerialErr;
    private javax.swing.JTextField SerialTxt;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Year;
    private javax.swing.JLabel YearErr;
    private javax.swing.JTextField YearTxt;
    private javax.swing.JLabel location;
    // End of variables declaration//GEN-END:variables
}
