/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package User;

import Model.Car;
import Model.Carlist;

/**
 *
 * @author yashjain
 */
public class DetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailsJPanel
     */
    Carlist history;
    Car selectedData;
    public DetailsJPanel(Carlist history) {
        initComponents();
        this.history = history;
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        Brand = new javax.swing.JLabel();
        BrandTxt = new javax.swing.JTextField();
        Model = new javax.swing.JLabel();
        ModelTxt = new javax.swing.JTextField();
        ModelNo = new javax.swing.JLabel();
        ModelNoTxt = new javax.swing.JTextField();
        Year = new javax.swing.JLabel();
        YearTxt = new javax.swing.JTextField();
        location = new javax.swing.JLabel();
        LocationTxt = new javax.swing.JTextField();
        Serial = new javax.swing.JLabel();
        SerialTxt = new javax.swing.JTextField();
        Operator = new javax.swing.JLabel();
        OperatorTxt = new javax.swing.JTextField();
        Available = new javax.swing.JLabel();
        AvailableY = new javax.swing.JRadioButton();
        AvailableN = new javax.swing.JRadioButton();
        MC = new javax.swing.JLabel();
        MCY = new javax.swing.JRadioButton();
        Seat = new javax.swing.JLabel();
        SeatTxt = new javax.swing.JTextField();
        SeatErr = new javax.swing.JLabel();
        MCN = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(240, 248, 255));

        Title.setBackground(java.awt.Color.white);
        Title.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 83, 170));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("View Details");

        Name.setForeground(new java.awt.Color(72, 72, 72));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Name.setText("Name");

        NameTxt.setEditable(false);
        NameTxt.setEnabled(false);

        Brand.setForeground(new java.awt.Color(72, 72, 72));
        Brand.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Brand.setText("Car Brand");

        BrandTxt.setEditable(false);
        BrandTxt.setEnabled(false);

        Model.setForeground(new java.awt.Color(72, 72, 72));
        Model.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Model.setText("Car Model");

        ModelTxt.setEditable(false);
        ModelTxt.setEnabled(false);

        ModelNo.setForeground(new java.awt.Color(72, 72, 72));
        ModelNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ModelNo.setText("Car Model No");

        ModelNoTxt.setEditable(false);
        ModelNoTxt.setEnabled(false);

        Year.setForeground(new java.awt.Color(72, 72, 72));
        Year.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Year.setText("Manufacture Year");

        YearTxt.setEditable(false);
        YearTxt.setEnabled(false);

        location.setForeground(new java.awt.Color(72, 72, 72));
        location.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        location.setText("Location");

        LocationTxt.setEditable(false);
        LocationTxt.setEnabled(false);

        Serial.setForeground(new java.awt.Color(72, 72, 72));
        Serial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Serial.setText("Serial No");

        SerialTxt.setEditable(false);
        SerialTxt.setEnabled(false);

        Operator.setForeground(new java.awt.Color(72, 72, 72));
        Operator.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Operator.setText("Operator");

        OperatorTxt.setEditable(false);
        OperatorTxt.setEnabled(false);

        Available.setForeground(new java.awt.Color(72, 72, 72));
        Available.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Available.setText("Available");

        AvailableY.setForeground(new java.awt.Color(72, 72, 72));
        AvailableY.setSelected(true);
        AvailableY.setText("Yes");
        AvailableY.setEnabled(false);
        AvailableY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailableYActionPerformed(evt);
            }
        });

        AvailableN.setForeground(new java.awt.Color(72, 72, 72));
        AvailableN.setText("No");
        AvailableN.setEnabled(false);
        AvailableN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvailableNActionPerformed(evt);
            }
        });

        MC.setForeground(new java.awt.Color(72, 72, 72));
        MC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        MC.setText("Maintenance Certificate");

        MCY.setForeground(new java.awt.Color(72, 72, 72));
        MCY.setSelected(true);
        MCY.setText("Yes");
        MCY.setEnabled(false);
        MCY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCYActionPerformed(evt);
            }
        });

        Seat.setForeground(new java.awt.Color(72, 72, 72));
        Seat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Seat.setText("Seat");

        SeatTxt.setEditable(false);
        SeatTxt.setEnabled(false);

        SeatErr.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        SeatErr.setForeground(java.awt.Color.red);

        MCN.setForeground(new java.awt.Color(72, 72, 72));
        MCN.setText("No");
        MCN.setEnabled(false);
        MCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MC, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Brand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Model, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModelNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Year, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Serial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Operator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Available, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Seat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ModelNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OperatorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MCY)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MCN)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SeatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeatErr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AvailableY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AvailableN))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Brand)
                            .addComponent(BrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Model)
                            .addComponent(ModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModelNo)
                            .addComponent(ModelNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Year)
                            .addComponent(YearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(location)
                            .addComponent(LocationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Serial)
                            .addComponent(SerialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Operator)
                            .addComponent(OperatorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Seat, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatErr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Available)
                            .addComponent(AvailableY)
                            .addComponent(AvailableN))
                        .addGap(18, 18, 18)
                        .addComponent(MC))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MCY)
                        .addComponent(MCN)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AvailableYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailableYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvailableYActionPerformed

    private void AvailableNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvailableNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvailableNActionPerformed

    private void MCYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MCYActionPerformed

    private void MCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MCNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Available;
    private javax.swing.JRadioButton AvailableN;
    private javax.swing.JRadioButton AvailableY;
    private javax.swing.JLabel Brand;
    private javax.swing.JTextField BrandTxt;
    private javax.swing.JTextField LocationTxt;
    private javax.swing.JLabel MC;
    private javax.swing.JRadioButton MCN;
    private javax.swing.JRadioButton MCY;
    private javax.swing.JLabel Model;
    private javax.swing.JLabel ModelNo;
    private javax.swing.JTextField ModelNoTxt;
    private javax.swing.JTextField ModelTxt;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel Operator;
    private javax.swing.JTextField OperatorTxt;
    private javax.swing.JLabel Seat;
    private javax.swing.JLabel SeatErr;
    private javax.swing.JTextField SeatTxt;
    private javax.swing.JLabel Serial;
    private javax.swing.JTextField SerialTxt;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Year;
    private javax.swing.JTextField YearTxt;
    private javax.swing.JLabel location;
    // End of variables declaration//GEN-END:variables

    private void setData() {
        selectedData = history.getSelectedView();
        String available = selectedData.getAvaliable();
        String mc = selectedData.getMc();
        NameTxt.setText(selectedData.getName());
        BrandTxt.setText(selectedData.getBrand());
        ModelTxt.setText(selectedData.getModel());
        ModelNoTxt.setText(selectedData.getModelNo());
        YearTxt.setText(String.valueOf(selectedData.getYear()));
        LocationTxt.setText(selectedData.getLocation());
        SerialTxt.setText(selectedData.getSerialNo());
        SeatTxt.setText(String.valueOf(selectedData.getSeat()));
        OperatorTxt.setText(selectedData.getOperator());
        if(available.equals("Yes")){
            AvailableY.setSelected(true);
            AvailableN.setSelected(false);
        }else{
            AvailableY.setSelected(false);
            AvailableN.setSelected(true);
        }
        if(mc.equals("Yes")){
            MCY.setSelected(true);
            MCN.setSelected(false);
        }else{
            MCY.setSelected(false);
            MCN.setSelected(true);
        }
    }
}
