/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Patient;

import Model.Patient;
import Model.PatientDirectory;
import Model.PersonDirectory;
import Person.*;
import UI.MainJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author yashjain
 */
public class PatientJFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserJFrame
     */
    static PatientDirectory patientHistory;
    static PersonDirectory personHistory;
    public PatientJFrame(PatientDirectory patientHistory, PersonDirectory personHistory) {
        initComponents();
        this.patientHistory = patientHistory;
        this.personHistory = personHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPanel = new javax.swing.JSplitPane();
        Action = new javax.swing.JPanel();
        Create = new javax.swing.JButton();
        View = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        ViewDetails = new javax.swing.JButton();
        Encouter = new javax.swing.JButton();
        VitalStats = new javax.swing.JButton();
        Workstation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPanel.setBackground(new java.awt.Color(240, 248, 255));
        SplitPanel.setDividerSize(15);

        Action.setBackground(new java.awt.Color(240, 248, 255));
        Action.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 217, 220), 1, true));
        Action.setPreferredSize(new java.awt.Dimension(200, 468));

        Create.setBackground(new java.awt.Color(0, 83, 170));
        Create.setForeground(new java.awt.Color(255, 255, 255));
        Create.setText("CREATE");
        Create.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Create.setDoubleBuffered(true);
        Create.setFocusCycleRoot(true);
        Create.setFocusTraversalPolicyProvider(true);
        Create.setPreferredSize(new java.awt.Dimension(129, 37));
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        View.setBackground(new java.awt.Color(0, 83, 170));
        View.setForeground(new java.awt.Color(255, 255, 255));
        View.setText("VIEW");
        View.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        View.setDoubleBuffered(true);
        View.setFocusCycleRoot(true);
        View.setFocusTraversalPolicyProvider(true);
        View.setPreferredSize(new java.awt.Dimension(129, 37));
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(0, 83, 170));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("BACK");
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Back.setDoubleBuffered(true);
        Back.setFocusCycleRoot(true);
        Back.setFocusTraversalPolicyProvider(true);
        Back.setPreferredSize(new java.awt.Dimension(129, 37));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        ViewDetails.setBackground(new java.awt.Color(0, 83, 170));
        ViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        ViewDetails.setText("DETAILS");
        ViewDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ViewDetails.setDoubleBuffered(true);
        ViewDetails.setFocusCycleRoot(true);
        ViewDetails.setFocusTraversalPolicyProvider(true);
        ViewDetails.setPreferredSize(new java.awt.Dimension(129, 37));
        ViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsActionPerformed(evt);
            }
        });

        Encouter.setBackground(new java.awt.Color(0, 83, 170));
        Encouter.setForeground(new java.awt.Color(255, 255, 255));
        Encouter.setText("APPOINTMENT");
        Encouter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Encouter.setDoubleBuffered(true);
        Encouter.setFocusCycleRoot(true);
        Encouter.setFocusTraversalPolicyProvider(true);
        Encouter.setPreferredSize(new java.awt.Dimension(129, 37));
        Encouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncouterActionPerformed(evt);
            }
        });

        VitalStats.setBackground(new java.awt.Color(0, 83, 170));
        VitalStats.setForeground(new java.awt.Color(255, 255, 255));
        VitalStats.setText("Vital Stat");
        VitalStats.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VitalStats.setDoubleBuffered(true);
        VitalStats.setFocusCycleRoot(true);
        VitalStats.setFocusTraversalPolicyProvider(true);
        VitalStats.setPreferredSize(new java.awt.Dimension(129, 37));
        VitalStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VitalStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActionLayout = new javax.swing.GroupLayout(Action);
        Action.setLayout(ActionLayout);
        ActionLayout.setHorizontalGroup(
            ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Create, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Encouter, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(VitalStats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ActionLayout.setVerticalGroup(
            ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(ViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Encouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(VitalStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        SplitPanel.setLeftComponent(Action);

        Workstation.setBackground(new java.awt.Color(240, 248, 255));
        Workstation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 217, 220), 1, true));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 83, 170));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Life");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout WorkstationLayout = new javax.swing.GroupLayout(Workstation);
        Workstation.setLayout(WorkstationLayout);
        WorkstationLayout.setHorizontalGroup(
            WorkstationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkstationLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        WorkstationLayout.setVerticalGroup(
            WorkstationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkstationLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 257, Short.MAX_VALUE))
        );

        SplitPanel.setRightComponent(Workstation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        CreateJPanels createJPanel = new CreateJPanels(patientHistory, personHistory);
        SplitPanel.setRightComponent(createJPanel);
    }//GEN-LAST:event_CreateActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        ViewsJPanel viewJPanels = new ViewsJPanel(patientHistory, personHistory);
        SplitPanel.setRightComponent(viewJPanels);
    }//GEN-LAST:event_ViewActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void ViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsActionPerformed
        // TODO add your handling code here:
       Patient SelectedRow = patientHistory.getSelectedView();
       if(SelectedRow != null){
        ViewDetailJPanel viewDetailJPanel = new ViewDetailJPanel(patientHistory, personHistory);
        SplitPanel.setRightComponent(viewDetailJPanel);
       }else{
           JOptionPane.showMessageDialog(this, "Please Selected Item From the Table", "Error message", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_ViewDetailsActionPerformed

    private void EncouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncouterActionPerformed
        // TODO add your handling code here:
        Patient SelectedRow = patientHistory.getSelectedView();
       if(SelectedRow != null){
        EncouterJPanel encouterJPanel = new EncouterJPanel(patientHistory);
        SplitPanel.setRightComponent(encouterJPanel);
        }else{
           JOptionPane.showMessageDialog(this, "Please Selected Item From the Table", "Error message", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_EncouterActionPerformed

    private void VitalStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VitalStatsActionPerformed
        // TODO add your handling code here:
        VitalSignJPanel vitalSignJPanel = new VitalSignJPanel(patientHistory, personHistory);
        SplitPanel.setRightComponent(vitalSignJPanel);
    }//GEN-LAST:event_VitalStatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientJFrame(patientHistory, personHistory).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Action;
    private javax.swing.JButton Back;
    private javax.swing.JButton Create;
    private javax.swing.JButton Encouter;
    private javax.swing.JSplitPane SplitPanel;
    private javax.swing.JButton View;
    private javax.swing.JButton ViewDetails;
    private javax.swing.JButton VitalStats;
    private javax.swing.JPanel Workstation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
