/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patient;

import Model.Encounter;
import Model.Patient;
import Model.PatientDirectory;
import Person.*;
import Model.Person;
import Model.PersonDirectory;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yashjain
 */
public class ViewsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingJPanel
     */
    PatientDirectory patientHistory;
    PersonDirectory personHistory;
    String sex = "Male";
    String community = "Test1";
    ArrayList<Patient> filterList;
    ArrayList<Encounter> encounterList;
    public ViewsJPanel(PatientDirectory patientHistory, PersonDirectory personHistory) {
        initComponents();
        this.patientHistory = patientHistory;
        filterList = new ArrayList<Patient>();
        filterData();
//        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        FName = new javax.swing.JLabel();
        FNameTxt = new javax.swing.JTextField();
        FName1 = new javax.swing.JLabel();
        LNameTxt = new javax.swing.JTextField();
        FName2 = new javax.swing.JLabel();
        PIDTxt = new javax.swing.JTextField();
        FName3 = new javax.swing.JLabel();
        ContactTxt = new javax.swing.JTextField();
        FName4 = new javax.swing.JLabel();
        CityTxt = new javax.swing.JTextField();
        FName5 = new javax.swing.JLabel();
        FName6 = new javax.swing.JLabel();
        AgeMinTxt = new javax.swing.JTextField();
        AgeMaxTxt = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        FName7 = new javax.swing.JLabel();
        Male = new javax.swing.JCheckBox();
        Female = new javax.swing.JCheckBox();
        Test1 = new javax.swing.JCheckBox();
        Test2 = new javax.swing.JCheckBox();
        Test3 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 248, 255));

        jLabel2.setBackground(new java.awt.Color(240, 248, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 83, 170));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Life");
        jLabel2.setToolTipText("");

        jSplitPane1.setBorder(null);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));

        FName.setForeground(new java.awt.Color(72, 72, 72));
        FName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName.setText("First Name");

        FName1.setForeground(new java.awt.Color(72, 72, 72));
        FName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName1.setText("Last Name");

        LNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameTxtActionPerformed(evt);
            }
        });

        FName2.setForeground(new java.awt.Color(72, 72, 72));
        FName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName2.setText("Person ID");

        FName3.setForeground(new java.awt.Color(72, 72, 72));
        FName3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName3.setText("Contact No");

        FName4.setForeground(new java.awt.Color(72, 72, 72));
        FName4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName4.setText("City");

        FName5.setForeground(new java.awt.Color(72, 72, 72));
        FName5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName5.setText("Sex");

        FName6.setForeground(new java.awt.Color(72, 72, 72));
        FName6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName6.setText("Age");

        Reset.setBackground(new java.awt.Color(0, 83, 170));
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("RESET");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(0, 83, 170));
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(0, 83, 170));
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("SEARCH");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        FName7.setForeground(new java.awt.Color(72, 72, 72));
        FName7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName7.setText("Community");

        Male.setForeground(new java.awt.Color(72, 72, 72));
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        Female.setForeground(new java.awt.Color(72, 72, 72));
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });

        Test1.setForeground(new java.awt.Color(72, 72, 72));
        Test1.setText("Test1");
        Test1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test1ActionPerformed(evt);
            }
        });

        Test2.setForeground(new java.awt.Color(72, 72, 72));
        Test2.setText("Test2");
        Test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test2ActionPerformed(evt);
            }
        });

        Test3.setForeground(new java.awt.Color(72, 72, 72));
        Test3.setText("Test3");
        Test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FName4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(FNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FName3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FName7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Test1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Test2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Test3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FName5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FName6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Female))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AgeMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(AgeMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Delete, Reset, Search});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName)
                    .addComponent(FNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FName3)
                    .addComponent(ContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FName5)
                    .addComponent(Male)
                    .addComponent(Female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName1)
                    .addComponent(FName4)
                    .addComponent(CityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FName6)
                    .addComponent(LNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeMaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName2)
                    .addComponent(PIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FName7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Test1)
                    .addComponent(Test2)
                    .addComponent(Test3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Delete, Reset, Search});

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(240, 248, 255));

        jScrollPane1.setBorder(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(72, 72, 72));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Person Id", "First Name", "Last Name", "Sex", "Age", "Age Group", "Contact No", "Address", "City", "Community"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 83, 170));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vital Sign");

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doc Name", "Ward Name", "Clinic Name", "First Name", "Last Name", "Respiratory Rate", "Heart Rate", "Blood Pressure", "Weight", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameTxtActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        filterData();
    }//GEN-LAST:event_SearchActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        FNameTxt.setText("");
        LNameTxt.setText("");
        PIDTxt.setText("");
        ContactTxt.setText("");
        CityTxt.setText("");
        AgeMinTxt.setText("");
        AgeMaxTxt.setText("");
        Test1.setSelected(false);
        Test2.setSelected(false);
        Test3.setSelected(false);
        Male.setSelected(false);
        Female.setSelected(false);
        SearchActionPerformed(evt);
    }//GEN-LAST:event_ResetActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void Test1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Test1ActionPerformed

    private void Test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Test2ActionPerformed

    private void Test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Test3ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select Row from the table to delete", "Error Message",JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Patient selectedRow = (Patient)model.getValueAt(rowIndex, 0);
        JOptionPane.showMessageDialog(this, "Data Deleted Successfully");
        rowIndex = 0;
        Person person = null;
             for(Person i: personHistory.getPersonHistory()){
                if(selectedRow.getPersonId() == i.getPersonId()){
                    person = i;
                    break;
                }
                rowIndex++;
            }
        personHistory.deleteData(person);
        patientHistory.deleteData(selectedRow);
        SearchActionPerformed(evt);
    }//GEN-LAST:event_DeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         Patient selectedRow = (Patient)model.getValueAt(rowIndex, 0);
         patientHistory.setSelectedView(selectedRow);
         populateVitalTable(selectedRow);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeMaxTxt;
    private javax.swing.JTextField AgeMinTxt;
    private javax.swing.JTextField CityTxt;
    private javax.swing.JTextField ContactTxt;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel FName;
    private javax.swing.JLabel FName1;
    private javax.swing.JLabel FName2;
    private javax.swing.JLabel FName3;
    private javax.swing.JLabel FName4;
    private javax.swing.JLabel FName5;
    private javax.swing.JLabel FName6;
    private javax.swing.JLabel FName7;
    private javax.swing.JTextField FNameTxt;
    private javax.swing.JCheckBox Female;
    private javax.swing.JTextField LNameTxt;
    private javax.swing.JCheckBox Male;
    private javax.swing.JTextField PIDTxt;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Search;
    private javax.swing.JCheckBox Test1;
    private javax.swing.JCheckBox Test2;
    private javax.swing.JCheckBox Test3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
private void populateTable(){
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    for(Patient cl: filterList){
        Object[] row = new Object[10];
        row[0] = cl;
        row[1] = cl.getFirstName();
        row[2] = cl.getLastName();
        row[3] = cl.getSex();
        row[4] = cl.getAge();
        row[5] = cl.getAgeType();
        row[6] = cl.getContact();
        row[7] = cl.getHouse();
        row[8] = cl.getCity();
        row[9] = cl.getCommunity();
        model.addRow(row);
      }
    }

    private void filterData() {
        filterList = patientHistory.getPatientHistory();
          String firstName = FNameTxt.getText();
          String lastName = LNameTxt.getText();
          int ageMin = 0;
          int ageMax = 100;
          String city = CityTxt.getText();
          String personId = PIDTxt.getText();
          long contact = 0l;
          
           if(!AgeMinTxt.getText().trim().isEmpty()){
            try {
                ageMin = Integer.parseInt(AgeMinTxt.getText());
                } catch (NumberFormatException nfe) {
                     JOptionPane.showMessageDialog(this, "Age Min can only be numbers", "Error Message",JOptionPane.ERROR_MESSAGE);                
                     return;
                }
             }

            if(!AgeMaxTxt.getText().trim().isEmpty()){
             try {
                ageMax = Integer.parseInt(AgeMaxTxt.getText());
                } catch (NumberFormatException nfe) {
                     JOptionPane.showMessageDialog(this, "Age Max can only be numbers", "Error Message",JOptionPane.ERROR_MESSAGE);                
                     return;
                }
            }
            
            if(!AgeMinTxt.getText().trim().isEmpty() && !AgeMaxTxt.getText().trim().isEmpty()){
            if(Integer.parseInt(AgeMinTxt.getText()) >= Integer.parseInt(AgeMaxTxt.getText())){
                JOptionPane.showMessageDialog(this, "Seat Min Value should not be greater than or equal to Max Value", "Error Message",JOptionPane.ERROR_MESSAGE);                
                return;
            }
        }
        
        Predicate<Patient> fname = e -> (e.getFirstName().toLowerCase() == null ? firstName == null : e.getFirstName().toLowerCase().indexOf(firstName) >= 0);
        Predicate<Patient> lname = e -> (e.getLastName().toLowerCase() == null ? lastName == null : e.getLastName().toLowerCase().indexOf(lastName) >= 0);
        Predicate<Patient> cityName = e -> (e.getCity().toLowerCase() == null ? city == null : e.getCity().toLowerCase().indexOf(city) >= 0);
        Predicate<Patient> Id = e -> (e.getPersonId().toLowerCase() == null ? personId == null : e.getPersonId().toLowerCase().indexOf(personId) >= 0);
        Predicate<Patient> Males = e -> (e.getSex() == null && !Male.isSelected() ? null : e.getSex().equals("Male"));
        Predicate<Patient> Females = e -> (e.getSex() == null && !Female.isSelected() ? null : e.getSex().equals("Female"));
        Predicate<Patient> Test1s = e -> (e.getCommunity() == null && !Test1.isSelected() ? null : e.getCommunity().equals("Test1"));
        Predicate<Patient> Test2s = e -> (e.getCommunity() == null && !Test2.isSelected() ? null : e.getCommunity().equals("Test2"));
        Predicate<Patient> Test3s = e -> (e.getCommunity() == null && !Test3.isSelected() ? null : e.getCommunity().equals("Test3"));
        
         filterList = (ArrayList<Patient>) filterList.stream()
                .filter(fname.and(lname).and(cityName).and(Id))
                .collect(Collectors.toList());
        if(!AgeMinTxt.getText().trim().isEmpty() || !AgeMaxTxt.getText().trim().isEmpty()){
            final var minSeats = !AgeMinTxt.getText().trim().isEmpty()? Integer.parseInt(AgeMinTxt.getText()) : 2;
            final var maxSeats = !AgeMaxTxt.getText().trim().isEmpty() ? Integer.parseInt(AgeMaxTxt.getText()) : 100;
            Predicate<Person> Seat = e -> (minSeats <= e.getAge() && maxSeats >=e.getAge());
            filterList = (ArrayList<Patient>) filterList.stream()
                    .filter(Seat)
                    .collect(Collectors.toList());
        }
        
        if(Male.isSelected() && !Female.isSelected()){
             filterList = (ArrayList<Patient>) filterList.stream()
                    .filter(Males)
                    .collect(Collectors.toList());
        }
        if(Female.isSelected() && !Male.isSelected()){
             filterList = (ArrayList<Patient>) filterList.stream()
                    .filter(Females)
                    .collect(Collectors.toList());
        }
        if(Test1.isSelected() && !Test2.isSelected() && !Test3.isSelected()){
             filterList = (ArrayList<Patient>) filterList.stream()
                    .filter(Test1s)
                    .collect(Collectors.toList());
        }
        if(Test2.isSelected() && !Test1.isSelected() && !Test3.isSelected()){
             filterList = (ArrayList<Patient>) filterList.stream()
                    .filter(Test2s)
                    .collect(Collectors.toList());
        }
        if(Test3.isSelected() && !Test1.isSelected() && !Test2.isSelected()){
             filterList = (ArrayList<Patient>) filterList.stream()
                    .filter(Test3s)
                    .collect(Collectors.toList());
        }
      populateTable();
    }

    private void populateVitalTable(Patient selectedRow) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        encounterList = selectedRow.getEncounterHistory().getEncounterHistory();
        for(Encounter cl: encounterList){
            Object[] row = new Object[10];
            row[0] = cl;
            row[1] = cl.getWardCategory();
            row[2] = cl.getClinicName();
            row[3] = selectedRow.getFirstName();
            row[4] = selectedRow.getLastName();
            row[5] = cl.getVital().getRespiratoryRate();
            row[6] = cl.getVital().getHeartRate();
            row[7] = cl.getVital().getBloodPressure();
            row[8] = cl.getVital().getWeight();
            row[9] = cl.getVital().getTime();
            model.addRow(row);
          } 
    }
}
